#!/bin/bash

which -s brew
if [[ $? != 0 ]] ; then
    echo "Installing homebrew..."
    sleep 1
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo '# Set PATH, MANPATH, etc., for Homebrew.' >> ~/.zprofile
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

function installBrew() {
    if [ ! -d "/usr/local/Cellar/$1" ]; then
        echo "Installing $1..."
        sleep 1
        brew install $1 
    else
      echo "$1 is already installed."
    fi
}

function installCask() {
    if [ ! -d "/usr/local/Caskroom/$1" ]; then
        echo "Installing $1..."
        sleep 1
        brew install --cask $1 
    else
      echo "$1 is already installed."
    fi
}

installBrew tmux
installBrew node
installBrew yarn
installBrew zsh
installBrew fzf
installCask telegram
installCask spectacle
installCask spotify
installCask iterm2
installCask karabiner-elements

if [ ! -d "/Library/Developer/CommandLineTools" ]; then
    xcode-select --install
fi

# Install Vim plugin manager
echo "Setting up vim and tmux config...";
if [ ! -d "$HOME/.vim/bundle/Vundle.vim/" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

# Get files from dotfiles repo
git clone https://github.com/cynthi-a/dotfiles.git $TMPDIR/dotfiles
cp $TMPDIR/dotfiles/.vimrc ~/.vimrc
cp $TMPDIR/dotfiles/.tmux.conf ~/.tmux.conf
cp $TMPDIR/dotfiles/.gitignore ~/.gitignore_global
echo "Setting up aliases..."
cp $TMPDIR/dotfiles/.bashrc ~/.bashrc
rm -rf $TMPDIR/dotfiles

# Source configuration files
echo "Sourcing config files..."
tmux source-file ~/.tmux.conf
git config --global core.excludesfile ~/.gitignore

echo "Installing vim plugins..."
vim +PluginInstall +qall

echo "Maximising key repeat..."
defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms);
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

echo "Disable press and hold for VS Code"
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

echo "Install Oh My Zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Done!"
